version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/php:8.1-node
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: sudo composer self-update --2
      - run: composer install -n 
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    resource_class: small
    docker:
      - image: cimg/php:8.1-node
        environment:
          TZ: 'Asia/Tokyo'
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
