services:
  # service
  sqs.client:
    class: Aws\Sqs\SqsClient
    arguments: 
      - { region: '%env(string:AWS_REGION)%', version: '2012-11-05' }
  message.receiver:
    class: HSawai\SQSConnectivityChecker\Service\Receiver
    arguments:
      $client: '@sqs.client' 
  message.sender:
    class: HSawai\SQSConnectivityChecker\Service\Sender
    arguments:
      $client: '@sqs.client'
  # command
  command.receiver:
    class: HSawai\SQSConnectivityChecker\Command\ReceiverCommand
    arguments:
      $receiver: '@message.receiver'
  command.sender:
    class: HSawai\SQSConnectivityChecker\Command\SenderCommand
    arguments:
      $sender: '@message.sender'
  
  # general
  app:
    class: Symfony\Component\Console\Application
    calls:
      - add: ['@command.receiver']
      - add: ['@command.sender']
    public: true