services:
  # service
  sqs.client:
    class: Aws\Sqs\SqsClient
  message.sender:
    class: Quartetcom\SQSConnectivityChecker\Service\Sender
    argument:
      $client: '@sqs.client'
  # command
  command.sender:
    class: Quartetcom\SQSConnectivityChecker\Command\SenderCommand
    arguments:
      $sender: '@message.sender'
  # general
  app:
    class: Symfony\Component\Console\Application
    calls:
      - add: ['@command.message']
    public: true